tunnel: 5409738b-c479-4c4a-b0c4-6dad6c9fdc3b
credentials-file: C:\Users\Apriansyah Dimas\.cloudflared\5409738b-c479-4c4a-b0c4-6dad6c9fdc3b.json

ingress:
  - hostname: portal.imajinasset.biz.id
    service: http://localhost:3001
  - hostname: app.imajinasset.biz.id
    service: http://localhost:3001
  - service: http_status:404