tunnel: 894bdbac-cb3c-4230-aacd-99a71f86b02a
credentials-file: C:\Users\Apriansyah Dimas\.cloudflared\894bdbac-cb3c-4230-aacd-99a71f86b02a.json

ingress:
  - hostname: imajinasset.biz.id
    service: http://localhost:3000
  - hostname: app.imajinasset.biz.id
    service: http://localhost:3000
  - service: http_status:404
