tunnel: imajinasset
credentials-file: C:UsersApriansyah Dimas.cloudflaredf8217f1d-3921-4f0c-985f-352c8a5d4e7b.json

ingress:
- hostname: app.imajinasset.biz.id
service: http://localhost:3001
- service: http_status:404
