tunnel: f8217f1d-3921-4f0c-985f-352c8a5d4e7b
credentials-file: C:\Users\Apriansyah Dimas\.cloudflared\f8217f1d-3921-4f0c-985f-352c8a5d4e7b.json

ingress:
  - hostname: "*.imajinasset.biz.id"
    service: http://localhost:3002
  - hostname: imajinasset.biz.id
    service: http://localhost:3002
  - service: http_status:404